### ISSUE TITLE
library has hard limit on  file size by default I can't fix it. if I upload more then 1 MB it saying 'request file size too long'

### ISSUE THREAD

**Issue by 0xMALVEE** [Blazity/nest-file-fastify#11]
library has hard limit on  file size by default I can't fix it. if I upload more then 1 MB it saying 'request file size too long'
how can I put 15 MB limit no way I can find here
![image](https://github.com/Blazity/nest-file-fastify/assets/35369563/7c7b582e-304e-46ea-a670-9f51e667973a)

**Comment by ericjeker** [comment]
Hard to answer your question as you are not showing your code. 

But basically, you should be able to define this in your `main.ts` file:

```typescript
await app.register(multipart, {
    limits: {
      fileSize: 10 * 1024 * 1024 // 10MB,
    },
});
```

**Comment by 0xMALVEE** [comment]
> Hard to answer your question as you are not showing your code.
> 
> But basically, you should be able to define this in your `main.ts` file:
> 
> ```ts
> await app.register(multipart, {
>     limits: {
>       fileSize: 10 * 1024 * 1024 // 10MB,
>     },
> });
> ```

yes this is correct. I already figured it out forgot to close issue
