### ISSUE TITLE
[SOLVED] How to get original filename ?

### ISSUE THREAD

**Issue by Hoax017** [Blazity/nest-file-fastify#2]
Hello how to get original files uploaded names?

**Comment by JoCat** [comment]
You can use `DiskStorageFile`. It contains a field with the name of the uploaded file.

How to use:

```ts
import {
  DiskStorage,
  FileInterceptor,
  MemoryStorageFile,
  UploadedFile,
} from '@blazity/nest-file-fastify';

...

@UseInterceptors(FileInterceptor('file', { storage: new DiskStorage() }))
@Post('download')
async downloadFile(
  @UploadedFile() file: DiskStorageFile,
) {
  console.log(file);
}
```

And you will get something like this:

```js
{
  size: 1256,
  dest: 'C:\\Users\\...\\AppData\\Local\\Temp',
  filename: 'b4e10ca0241b161ec8013f62f3478cfd.png',
  originalFilename: '64x32.png',
  path: 'C:\\Users\\...\\AppData\\Local\\Temp\\b4e10ca0241b161ec8013f62f3478cfd.png',
  mimetype: 'image/png',
  encoding: '7bit',
  fieldname: 'file'
}
```

Actually `originalFilename` is what you need 😉

**Comment by simplenotezy** [comment]
@JoCat what about `MemoryStorageFile`?

**Comment by JoCat** [comment]
> @JoCat what about `MemoryStorageFile`?

Judging by the commit from a year ago (https://github.com/Blazity/nest-file-fastify/commit/c3e9a98647a78bdb73b1c3e25cf9ae596b30fb8c), the original title can now be deduced from it as well.

**Comment by faheemhameed** [comment]
Hello there,

I am trying to upload multiple files and get the file names using the below code:

```
  @UseInterceptors(
    FileFieldsInterceptor([
      { name: 'files', maxCount: 10 },
    ], { storage: new DiskStorage() })
  )
  @Post('upload-image')
  async downloadFile(
    @UploadedFiles() files: DiskStorageFile[]): Promise<void> {
    console.log("upload-image 111111");
    console.log(files);
  }
```

When calling the above URL the downloadFile method never gets called.  
The console.log("upload-image 111111") was never printed.

It worked well when I used @UploadedFile & FileInterceptor to upload single files.

I am not sure what I am doing wrongly here. Please shed some light on this.

My Angular file upload code is as below:
```

  uploadPhotos(event: Event) {
    const files = (event.target as HTMLInputElement).files;

    const formData = new FormData();
    Array.from(files).forEach((file) => {
      console.log(file);
      formData.append('file', file);
    });

    return this.http.post('/api/inventory/upload-image', formData).subscribe(
      (response) => {
        console.log('Files uploaded successfully');
      },
      (error) => {
        console.error('Error uploading files:', error);
      }
    );
  }
```

Thanks.

**Comment by faheemhameed** [comment]
Any ideas on the above?
